spring:
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS}
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      dialect: ${DB_DIALECT}
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: ${REDIRECT_URI}
            scope:
              - email
              - profile
        provider:
          google:
            token-uri: ${TOKEN-URI}
            user-info-uri: ${USER_INFO_URI}

  data:
    redis:
      host: 127.0.0.1
      port: 6379

jwt:
  secret:
    access-token: ${ACCESS_TOKEN_KEY}
    refresh-token: ${REFRESH_TOKEN_KEY}